services:
  db:
    image: postgres:17-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata

    user: "1000:1000"

    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

    ports:
      - ${DB_PORT}:5432
