services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sca
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    networks:
      - sisinf

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: sca
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: "Europe/Madrid"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02-data.sql
    ports:
      - "5432:5432"
    networks:
      - sisinf

networks:
  sisinf:
    driver: bridge

volumes:
  postgres_data: